language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install -e .[test]

before_install:
  - sudo rm -f /etc/boto.cfg
  - if [[ "${TRAVIS_PYTHON_VERSION}" = "2.7" ]]; then easy_install distribute; fi

script:
  - "fab check"
