name: CI

on: [pull_request]

jobs:
  ci:
    strategy:
      matrix:
        python: ['2.7', '3.6']
        os: ['windows-latest', 'macos-latest']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: python -m pip install --upgrade pip
      - run: pip install distribute
        if: matrix.python == '2.7'
      - run: pip install -e .[test]
      - run: invoke check
